description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: plughw:CARD=ICUSBAUDIO7D,DEV=0
    format: S16LE
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: false
    type: Alsa
  capture_samplerate: 44100
  chunksize: 64
  enable_rate_adjust: false
  multithreaded: null
  playback:
    channels: 2
    device: hw:CARD=ICUSBAUDIO7D,DEV=0
    format: S16LE
    type: Alsa
  queuelimit: 1
  rate_measure_interval: null
  resampler: null
  samplerate: 48000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: 0
filters:
  Gain:
    description: null
    parameters:
      gain: -0.7
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Left:
    description: null
    parameters:
      channel: 0
      filename: ../coeffs/Umik-vanster-stol-48.wav
      type: Wav
    type: Conv
  Mute:
    description: null
    parameters:
      gain: 0
      inverted: false
      mute: true
      scale: dB
    type: Gain
  Right:
    description: null
    parameters:
      channel: 0
      filename: ../coeffs/Umik-hoger-stol-48.wav
      type: Wav
    type: Conv
mixers: {}
pipeline:
- bypassed: null
  channels: null
  description: null
  names:
  - Gain
  type: Filter
- bypassed: null
  channels:
  - 0
  description: null
  names:
  - Left
  type: Filter
- bypassed: null
  channels:
  - 1
  description: null
  names:
  - Right
  type: Filter
processors: {}
title: Room-correction
